
from Klasse_Lernmotivation import Lernmotivationverwaltung

a = Lernmotivationverwaltung()

a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(7)
a.printStatus()
a.lernen(10)
a.printStatus()
a.lernen(10)
a.printStatus()